### ISSUE TITLE
unable to download with the -d flag

### ISSUE THREAD

**Issue by ryan-yap** [matlink/gplaycli#105]
I am getting the following error when I am trying to download the file. It used to be working a few days ago. The command i used was gplaycli -d com.yogavpn
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 4, in <module>
    __import__('pkg_resources').run_script('GPlayCli==0.2.12', 'gplaycli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/GPlayCli-0.2.12-py2.7.egg/EGG-INFO/scripts/gplaycli", line 553, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/GPlayCli-0.2.12-py2.7.egg/EGG-INFO/scripts/gplaycli", line 523, in main
    
  File "/usr/local/lib/python2.7/dist-packages/GPlayCli-0.2.12-py2.7.egg/EGG-INFO/scripts/gplaycli", line 181, in connect_to_googleplay_api
    
  File "/usr/local/lib/python2.7/dist-packages/GPlayCli-0.2.12-py2.7.egg/EGG-INFO/scripts/gplaycli", line 368, in raw_search
    
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 199, in search
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 183, in executeRequestApi2
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.4.0-py2.7.egg/google/protobuf/internal/python_message.py", line 757, in FromString
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.4.0-py2.7.egg/google/protobuf/internal/python_message.py", line 1072, in MergeFromString
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by matlink** [comment]
https://github.com/matlink/gplaycli/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by matlink** [comment]
Moreover, are you using token or your own credentials?

**Comment by nicktogo** [comment]
@matlink Met the same issue, using your token dispenser

**Comment by nicktogo** [comment]
When I execute the command with -v, it said that gplaycli is using the cached token, I guess that what happened: the cached token has expired and the code does not handle well with what google returns, so I tried to remove the cached token file and then gplaycli start to retrieve new token and work well, why would that happen?

**Comment by nicktogo** [comment]
After check the code, I think gplaycli does not check whether the token has expired?

**Comment by matlink** [comment]
Yes since version 0.2.8 gplaycli checks the token validity: https://github.com/matlink/gplaycli/commit/c4cafabb8d4a3b4f17e785dbb6b4373680327931

**Comment by matlink** [comment]
Update Gplaycli to version 3.2 and check again please
