### ISSUE TITLE
AttributeError: 'int' object has no attribute 'find' error with default config file

### ISSUE THREAD

**Issue by saidelike** [matlink/gplaycli#108]
Hi

When trying to use gplaycli with the default `~/.config/gplaycli/gplaycli.conf`

```
[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
android_ID=3d716411bf8bc802
language=fr_FR
token=True
token_url=https://matlink.fr/token/email/gplaycliacc@gmail.com

[Cache]
token=~/.cache/gplaycli/token
```

It fails with this error:
```
$ gplaycli -s com.android.chrome
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 551, in <module>
    main()
  File "/usr/local/bin/gplaycli", line 518, in main
    cli = GPlaycli(args, args.config)
  File "/usr/local/bin/gplaycli", line 73, in __init__
    for key, value in self.configparser.items("Credentials"):
  File "/usr/lib/python3.5/configparser.py", line 855, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 855, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 852, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 410, in _interpolate_some
    p = rest.find("%")
AttributeError: 'int' object has no attribute 'find'
```

I found a fix though. After adding `retries=2` to the config file

```
[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
android_ID=3d716411bf8bc802
language=fr_FR
token=True
token_url=https://matlink.fr/token/email/gplaycliacc@gmail.com
retries=2

[Cache]
token=~/.cache/gplaycli/token
```

It works fine.

```
$ gplaycli -s com.android.chrome
Title                               Creator           Size    Downloads       Last Update    AppID                           Version     Rating
Navigateur Google Chrome            Google Inc.       44.5MB  1 000 000 000+  19 sept. 2017  com.android.chrome              316309800   4.28
Chrome Beta                         Google Inc.       44.4MB  10 000 000+     27 sept. 2017  com.chrome.beta                 320203800   4.35
Chrome Dev                          Google Inc.       44.5MB  1 000 000+      26 sept. 2017  com.chrome.dev                  322300700   4.35
Bureau à distance Chrome            Google Inc.       5.8MB   10 000 000+     28 août 2017   com.google.chromeremotedesktop  316302000   4.34
쇼핑을 다 담다. G마켓                       G마켓               9.4MB   10 000 000+     25 sept. 2017  com.ebay.kr.gmarket             163         3.77
쇼핑에 상식을 채우다. G9                     G마켓               11.8MB  1 000 000+      26 sept. 2017  com.ebay.kr.g9                  83          4.40
Firefox. Naviguez librement         Mozilla           37.6MB  100 000 000+    16 août 2017   org.mozilla.firefox             2015506297  4.38
Android System WebView              Google Inc.       32.3MB  1 000 000 000+  19 sept. 2017  com.google.android.webview      316309800   4.38
AVG Antivirus Android Gratuit 2017  AVG Mobile        21.1MB  100 000 000+    1 sept. 2017   com.antivirus                   316337      4.50
UrlToPDF                            .:: DevDroid ::.  3.0MB   100 000+        4 sept. 2017   com.nop.urltopdf                145         4.15
```

- [x] Operating System: Ubuntu 16.04.3
- [x] GPlayCli version via `gplaycli -v`: 2.15 [Python3.5.2]
- [x] The way you installed `gplaycli`: `pip3 install gplaycli`, 
- [x] The authentication method: see above (default provided in repo)

Hope this helps fixing the bug :)

**Comment by matlink** [comment]
Update to version 2.16 to fix the issue
