### ISSUE TITLE
IndexError: list index out of range when appID is not found

### ISSUE THREAD

**Issue by saidelike** [matlink/gplaycli#109]
Hi,

When I search for this it errors but I would just expect it to return nothing.

```
$ gplaycli -s bonibon.ses.yukle
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 551, in <module>
    main()
  File "/usr/local/bin/gplaycli", line 539, in main
    cli.search(list(), args.search_string, nb_results, not args.paid)
  File "/usr/local/bin/gplaycli", line 369, in search
    results = self.raw_search(results_list, search_string, nb_results)
  File "/usr/local/bin/gplaycli", line 366, in raw_search
    return self.playstore_api.search(search_string, nb_results=nb_results).doc
  File "/usr/local/lib/python3.5/dist-packages/ext_libs/googleplay_api/googleplay.py", line 257, in search
    remaining = int(nb_results) - len(message.payload.searchResponse.doc[0].child)
IndexError: list index out of range
```

When I search for a sub part, it works fine:

```
$ gplaycli -s bonibon
Title                                          Creator                                           Size    Downloads    Last Update    AppID                           Version  Rating
Telecharger+Musique+Gratuite+MP3+Music+Player  MixerBox© - Music & MP3 Player App FREE DOWNLOAD  8.0MB   50 000 000+  14 sept. 2017  mbinc12.mb32b                   656      4.27
Bonibo                                         Eğitim Bilişim Ağı (EBA)                          20.0MB  1 000+       24 oct. 2016   tr.gov.eba.oyun.bonibo          1        4.37
Ongles En Acrylique                            bonibon                                           36.9MB  5 000+       24 sept. 2017  com.bonibon.AcrylicNails        2        4.44
Long Nails                                     bonibon                                           19.1MB  10 000+      21 mars 2017   com.bonibon.LongNails           1        4.47
Clous Parfaits                                 bonibon                                           31.3MB  1 000+       24 sept. 2017  com.bonibon.PerfectNails        2        4.14
Pantoufles En Crochet                          bonibon                                           25.9MB  5 000+       23 sept. 2017  com.bonibon.CrochetSlippers     2        4.52
French Nails                                   bonibon                                           20.7MB  500+         24 sept. 2017  com.bonibon.FrenchNails         2        4.50
Pro Nails                                      bonibon                                           32.9MB  100+         24 sept. 2017  com.bonibon.ProNails            3        5.00
Acrylic Nail Designs                           bonibon                                           26.0MB  1 000+       24 sept. 2017  com.bonibon.AcrylicNailDesigns  2        3.00
Haut À Crochet                                 bonibon                                           24.0MB  1 000+       23 sept. 2017  com.bonibon.CrochetTop          2        3.36
```

- [x] Operating System: Ubuntu 16.04.3
- [x] GPlayCli version via `gplaycli -v`: 2.15 [Python3.5.2]
- [x] The way you installed `gplaycli`: `pip3 install gplaycli`, 
- [x] The authentication method: see above (default provided in repo)

Hope this helps.

**Comment by jr3074** [comment]
i also got this problem, same with this issue https://github.com/matlink/gplaycli/issues/107
