### ISSUE TITLE
google.protobuf.message.DecodeError: Unexpected end-group tag

### ISSUE THREAD

**Issue by lucasduffey** [matlink/gplaycli#119]
**OS:** Ubuntu 16 LTS, fully patched
**Python version:** 3.4
**GPlayCli version:** 3.9 [Python3.5.2]

**Installation method**
* I've tried installing from master, apt, pip and I get similar problems

**Auth method**
using the example configuration file you have @ https://github.com/matlink/gplaycli/blob/master/gplaycli.conf

# example crash
```
user@computer:~/research/gplaycli$ gplaycli -s google
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.4', 'console_scripts', 'gplaycli')()
  File "/home/user/research/gplaycli/gplaycli/gplaycli.py", line 543, in main
    success, error = cli.connect_to_googleplay_api()
  File "/home/user/research/gplaycli/gplaycli/gplaycli.py", line 193, in connect_to_googleplay_api
    api.login(authSubToken=self.token, gsfId=int(self.gsfid,16))
  File "/home/user/.local/lib/python3.5/site-packages/gpapi/googleplay.py", line 200, in login
    self.search('firefox', 1, None)
  File "/home/user/.local/lib/python3.5/site-packages/gpapi/googleplay.py", line 274, in search
    data = self.executeRequestApi2(currentPath)
  File "/home/user/.local/lib/python3.5/site-packages/gpapi/googleplay.py", line 250, in executeRequestApi2
    message = googleplay_pb2.ResponseWrapper.FromString(response.content)
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.4.0-py3.5.egg/google/protobuf/internal/python_message.py", line 757, in FromString
    message.MergeFromString(s)
  File "/usr/local/lib/python3.5/dist-packages/protobuf-3.4.0-py3.5.egg/google/protobuf/internal/python_message.py", line 1072, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
```

**Comment by lucasduffey** [comment]
I was able to get this working 1-2 weeks ago, does google no longer allow the old conf file used for auth?

**Comment by lucasduffey** [comment]
I think deleting the cached token might solve this

**Comment by matlink** [comment]
did you upgraded ?

**Comment by lucasduffey** [comment]
yeah that was running the newest version from master

**Comment by matlink** [comment]
your example crash says GPlayCli==3.4
What's the gpapi version you got ?

**Comment by matlink** [comment]
Gplaycli version 3.10 should fix that issue

**Comment by wetterfroschdus** [comment]
Hey, just had the same thing happen, with the newest version.
Manually deleting the token works as a hotfix.
