### ISSUE TITLE
Error on token=False

### ISSUE THREAD

**Issue by muzzyrost** [matlink/gplaycli#121]
user@user-VirtualBox:~$ gplaycli -v -p -a -d com.mapswithme.maps.pro
[INFO] GPlayCli version 3.6 [Python3.5.2] 
[INFO] Configuration file is /home/user/.config/gplaycli/gplaycli.conf
Traceback (most recent call last):
  File "/home/user/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 532, in main
    success, error = cli.connect_to_googleplay_api()
  File "/home/user/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 184, in connect_to_googleplay_api
    if self.token is False:
AttributeError: 'GPlaycli' object has no attribute 'token'

**Comment by matlink** [comment]
Thanks for report. 3.7 should fix this.

**Comment by muzzyrost** [comment]
@matlink sorry but same problem for -t (token=True in conf file)

user@user-VirtualBox:~$ gplaycli -t -s com.mapswithme.maps.pro
Traceback (most recent call last):
  File "/home/user/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 531, in main
    cli = GPlaycli(args, args.config)
  File "/home/user/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 121, in __init__
    if self.token_enable:
AttributeError: 'GPlaycli' object has no attribute 'token_enable'

**Comment by matlink** [comment]
3.8 should fix.

**Comment by BBerastegui** [comment]
I run into the same issue on the latest version for `pip3`, had to add this:

`gpc.retrieve_token(force_new=True)`

From: https://github.com/matlink/gplaycli/issues/190

A little bit of documentation for using it as a module will be super helpful :)

Thanks for your work btw.

**Comment by matlink** [comment]
Yeah, I didn't spent much time since GPlayCli is not really designed to be used as a module. You better use @NoMore201 's googleplay-api if you want flexibility.
