### ISSUE TITLE
google.protobuf.message.DecodeError: Unexpected end-group tag

### ISSUE THREAD

**Issue by wetterfroschdus** [matlink/gplaycli#128]
Just had the same thing happen as in #119 , with the newest version (3.10).
Manually deleting the token works as a hotfix.

**Comment by matlink** [comment]
do you still have this issue?

**Comment by wetterfroschdus** [comment]
Yup.

**Comment by matlink** [comment]
what was the version of gpapi (`pip freeze | grep gpapi`)?

**Comment by wetterfroschdus** [comment]
gpapi==0.2

**Comment by matlink** [comment]
update it please, to version 0.3.1

**Comment by wetterfroschdus** [comment]
Hey, just updated it (also removed the cached token). Was able to download one apk, then it immediately threw that error again.

> Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 504, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 194, in connect_to_googleplay_api
    gsfId=gsfId)
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 193, in login
    self.search('firefox', 1, None)
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 288, in search
    data = self.executeRequestApi2(currentPath)
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 264, in executeRequestApi2
    message = googleplay_pb2.ResponseWrapper.FromString(response.content)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 757, in FromString
    message.MergeFromString(s)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1086, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by matlink** [comment]
Seems related to python 3.6 too, I'll dig deeper :D
