### ISSUE TITLE
Crash when the list contains whitespaces

### ISSUE THREAD

**Issue by enovella** [matlink/gplaycli#144]
**Fix:** `trim` line by line when parsing the list with `-F`

```
> gplaycli  -p -v -F mylist.txt
GPlayCli version 3.4 [Python3.4.3]
Configuration file is /home/edu/.config/gplaycli/gplaycli.conf
Using credentials to connect to API
Using plaintext password
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 557, in main
    cli.download_packages(args.packages_to_download)
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 421, in download_packages
    self.after_download)
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 295, in download_selection
    details = playstore_api.bulkDetails([item for item, item2 in list_of_packages_to_download])
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 322, in bulkDetails
    "application/x-protobuf")
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 252, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error retrieving information from server. [DF-BDA-04]'

```

**Comment by matlink** [comment]
Can you give me an example of list that crashes?

**Comment by enovella** [comment]
Umm....  

I'm afraid it was already deleted but any list with whitespaces.

**Comment by enovella** [comment]
Hi,

you fixed the current line but if there are empty lines also crashes.

`/media/xxxx/4tb/apks/apks.txt` is as follows:
```
com.example.app

```

```
[22:17 xxxx@sugar apks] > gplaycli  -p -v -F /media/xxxx/4tb/apks/apks.txt
[INFO] GPlayCli version 3.12 [Python3.4.3]
[INFO] Configuration file is /home/xxxx/.config/gplaycli/gplaycli.conf
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token: hQWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[INFO] Using auto retrieved token to connect to API
vacio: Error retrieving information from server. [DF-BDA-04]
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.12', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 561, in main
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 428, in download_packages
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 301, in download_selection
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 377, in bulkDetails
    "application/x-protobuf")
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 278, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error retrieving information from server. [DF-BDA-04]'

```
