### ISSUE TITLE
A simple error in an APK list breaks the entire run

### ISSUE THREAD

**Issue by enovella** [matlink/gplaycli#148]
# List to reproduce
apks.txt
```
7 com.example.com
com.example2.com
```

# Fix
Skip the line with a try-catch and log into stderr

# Output
```
[20:24 user@sugar apks] > gplaycli  -p -v -F /media/user/4tb/apks/apks.txt
[INFO] GPlayCli version 3.12 [Python3.4.3]
[INFO] Configuration file is /home/user/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
vacio: Error retrieving information from server. [DF-BDA-04]
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.12', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 561, in main
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 428, in download_packages
  File "/usr/local/lib/python3.4/dist-packages/GPlayCli-3.12-py3.4.egg/gplaycli/gplaycli.py", line 301, in download_selection
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 377, in bulkDetails
    "application/x-protobuf")
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 278, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error retrieving information from server. [DF-BDA-04]'

```

**Comment by matlink** [comment]
Duplicate #144

**Comment by matlink** [comment]
Which error are you mentionning? Whitespace or blank line?

**Comment by enovella** [comment]
blank line or non correct package name like `whateverinhere com.apksample`

**Comment by enovella** [comment]
The issue still exists in this version:
```
 > gplaycli -V
3.13 [Python3.4.3] 
```
