### ISSUE TITLE
cache file does not exists or is corrupted

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#161]
I'm getting the following error when using token. I can confirm that the cache token exists in the path with the token value.

```
root@kali:~/Desktop# gplaycli -v -p -d com.facebook.katama
[INFO] GPlayCli version 3.19 [Python3.6.4] 
[INFO] Configuration file is /root/.config/gplaycli/gplaycli.conf
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.19', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.6/dist-packages/GPlayCli-3.19-py3.6.egg/gplaycli/gplaycli.py", line 663, in main
  File "/usr/local/lib/python3.6/dist-packages/GPlayCli-3.19-py3.6.egg/gplaycli/gplaycli.py", line 148, in __init__
  File "/usr/local/lib/python3.6/dist-packages/GPlayCli-3.19-py3.6.egg/gplaycli/gplaycli.py", line 182, in retrieve_token
ValueError: not enough values to unpack (expected 2, got 1)
root@kali:~/Desktop#
```

OS: Kali Linux 64bit

**Comment by matlink** [comment]
what's the `token_url` in `/root/.config/gplaycli/gplaycli.conf`?
