### ISSUE TITLE
invalid literal for int() with base 16: 'found'

### ISSUE THREAD

**Issue by codeurimpulsif** [matlink/gplaycli#175]
Hi, I use a token dispenser (it seem to work fine) but GPlayCli throw me the following error.
I have the same error when using your token dispenser.

Informations:

- [ ] Operating System : Debian Stretch
- [ ] Python version when running `gplaycli` : 3.5.3
- [ ] GPlayCli version via `gplaycli -v` : 3.21
- [ ] The way you installed `gplaycli`: `pip install gplaycli`
- [ ] The authentication method: own token

Stacktrace :

```
[INFO] GPlayCli version 3.22 [Python3.5.3]
[INFO] Configuration file is /home/user/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
Traceback (most recent call last):
   File "/home/user/program/venv/bin/gplaycli", line 11, in <module>
     load_entry_point('GPlayCli==3.22', 'console_scripts', 'gplaycli')()
   File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 695, in main
     cli.download(args.packages_to_download)
   File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/hooks.py", line 8, in check_connection
     self.connect()
   File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 399, in connect
     gsfid = int(self.gsfid, 16)
 ValueError: invalid literal for int() with base 16: 'found'
```

**Comment by matlink** [comment]
Can you show me what's the content of `/home/user/.config/gplaycli/gplaycli.conf` and the content of the token cache file usually located at `~/.cache/gplaycli/token` please?

**Comment by codeurimpulsif** [comment]
`/home/user/.config/gplaycli/gplaycli.conf` contain : 
```
[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
timezone=CEST
```

and `~/.cache/gplaycli/token` : 
```
_QUKZq-ewuGu7qgwKOWFbM2EccE4NjUGrWDJySV8uWEfxQ5ZZBYNm45S6bJ-6j_6RJWS9Q. 35dc3da6ec3a61ab
```

And now the stacktrace is : 
```
Traceback (most recent call last):
  File "/home/user/program/venv/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 694, in main
    cli.download(args.packages_to_download)
  File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/home/user/program/venv/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 260, in download
   total_size = int(data_iter['file']['total_size'])
KeyError: 'file'
```

**Comment by codeurimpulsif** [comment]
It was effectively the protobuf version not up to date in my requirements.txt, now it work perfectly.

Thanks you for your help and tool :)
