### ISSUE TITLE
Unexpected end-group tag

### ISSUE THREAD

**Issue by ibrahimch** [matlink/gplaycli#183]
```
Ubuntu 16.04
python3 -V
Python 3.5.2
python -V
Python 2.7.12
GPlayCli version 3.21
Method: Installed using pip3
ConfigData:
[Credentials]
gmail_address=myemail
gmail_password=******
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
timezone=CEST
```
**I'm facing issue on every request**
Command `gplaycli -v -s Facebook`
Result
```
[INFO] GPlayCli version 3.21 [Python3.5.2]
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
RuntimeWarning: Unexpected end-group tag: Not all data was converted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 405, in connect
    gsfId=gsfid)
  File "/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py", line 205, in login
    self.search('firefox', 1, None)
  File "/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py", line 317, in search
    data = self.executeRequestApi2(currentPath)
  File "/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py", line 293, in executeRequestApi2
    message = googleplay_pb2.ResponseWrapper.FromString(response.content)
SystemError: <built-in method FromString of GeneratedProtocolMessageType object at 0x29a39b8> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 686, in main
    cli.search(args.search_string, nb_results, not args.paid)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 412, in connect
    self.refresh_token()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 464, in refresh_token
    self.retrieve_token(force_new=True)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 182, in retrieve_token
    token, gsfid = response.text.split(" ")
ValueError: too many values to unpack (expected 2)

```

**Comment by matlink** [comment]
Probably related to https://github.com/matlink/gplaycli/issues/170#issuecomment-388323442
I've fixed it temporarily. Is it ok for you?

**Comment by ibrahimch** [comment]
I updated AndroidId, Now Its Working Fine, Thanks
