### ISSUE TITLE
Problem with installation with v3.23

### ISSUE THREAD

**Issue by enovella** [matlink/gplaycli#186]
## Log:
```
edu@de11:~/tools$ sudo pip3 install gplaycli
The directory '/home/edu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/edu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gplaycli
  Downloading https://files.pythonhosted.org/packages/62/c6/07f2ee4415c95eb057677c0d6c8b067a1debd577e424c259980f21d9f300/GPlayCli-3.23.tar.gz
Requirement already satisfied: gpapi==0.4.2 in /usr/local/lib/python3.6/dist-packages (from gplaycli)
Requirement already satisfied: pyaxmlparser in /usr/local/lib/python3.6/dist-packages (from gplaycli)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from gpapi==0.4.2->gplaycli)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.6/dist-packages (from gpapi==0.4.2->gplaycli)
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from gpapi==0.4.2->gplaycli)
Requirement already satisfied: click==6.7 in /usr/local/lib/python3.6/dist-packages (from pyaxmlparser->gplaycli)
Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (from pyaxmlparser->gplaycli)
Installing collected packages: gplaycli
  Running setup.py install for gplaycli ... done
Successfully installed gplaycli-3.23
edu@de11:~/tools$ gplaycli 
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.23', 'console_scripts', 'gplaycli')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/gplaycli.py", line 30, in <module>
    from gpapi.googleplay import GooglePlayAPI
  File "/usr/local/lib/python3.6/dist-packages/gpapi/googleplay.py", line 14, in <module>
    from . import googleplay_pb2, config, utils
  File "/usr/local/lib/python3.6/dist-packages/gpapi/googleplay_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
edu@de11:~/tools$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by enovella** [comment]
Yeah it was that. :+1:

**Comment by enovella** [comment]
Fixed by https://github.com/matlink/gplaycli/issues/186#issuecomment-396147458

**Comment by spvkgn** [comment]
I have same error with latest gpapi 0.4.2 installed.
```
$ gplaycli 
Traceback (most recent call last):
  File "/home/pavel/.local/bin/gplaycli", line 7, in <module>
    from gplaycli.gplaycli import main
  File "/home/pavel/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 30, in <module>
    from gpapi.googleplay import GooglePlayAPI
  File "/home/pavel/.local/lib/python3.6/site-packages/gpapi/googleplay.py", line 14, in <module>
    from . import googleplay_pb2, config, utils
  File "/home/pavel/.local/lib/python3.6/site-packages/gpapi/googleplay_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
$ pip3 show gplaycli gpapi
Name: GPlayCli
Version: 3.23
Summary: GPlayCli, a Google play downloader command line interface
Home-page: https://github.com/matlink/gplaycli
Author: Matlink
Author-email: matlink@matlink.fr
License: AGPLv3
Location: /home/pavel/.local/lib/python3.6/site-packages
Requires: pyaxmlparser, gpapi
Required-by: 
---
Name: gpapi
Version: 0.4.2
Summary: Unofficial python api for google play
Home-page: https://github.com/NoMore201/googleplay-api
Author: NoMore201
Author-email: domenico.iezzi.201@gmail.com
License: MIT
Location: /home/pavel/.local/lib/python3.6/site-packages
Requires: requests, pycryptodome, protobuf
Required-by: GPlayCli
```
