### ISSUE TITLE
gplaycli doesn't work anymore 

### ISSUE THREAD

**Issue by stas-smedia** [matlink/gplaycli#194]
around 10 days ago suddenly stopped working 
with the following error:

```
# gplaycli -d com.facebook.katana
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 702, in main
    cli.download(args.packages_to_download)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 406, in connect
    gsfid = int(self.gsfid, 16)
ValueError: invalid literal for int() with base 16: 'request'
```

os: ubuntu 18.04

version:

```
gplaycli -v
[INFO] GPlayCli version 3.23 [Python3.6.5] 
[INFO] Configuration file is gplaycli.conf
[INFO] Using cached token.
```

config:
```
cat gplaycli.conf 
[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
```

**Comment by leegarrett** [comment]
See #191. Does deleting the token fix it for you? If yes, it's the same issue.
