### ISSUE TITLE
Issue with downloading

### ISSUE THREAD

**Issue by muzzyrost** [matlink/gplaycli#197]
```
ub@ub:~$ gplaycli -s youtube -v
[INFO] GPlayCli version 3.24 [Python3.6.6] 
[INFO] Configuration file is /home/ub/.config/gplaycli/gplaycli.conf
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
Traceback (most recent call last):
  File "/home/ub/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 714, in main
    cli.search(args.search_string, nb_results, not args.paid)
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 430, in connect
    gsfId=gsfid)
  File "/home/ub/.local/lib/python3.6/site-packages/gpapi/googleplay.py", line 223, in login
    raise SecurityCheckError()
gpapi.googleplay.SecurityCheckError
```
And with Token=True

```
ub@ub:~$ gplaycli -s youtube -v
[INFO] GPlayCli version 3.24 [Python3.6.6] 
[INFO] Configuration file is /home/ub/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
Traceback (most recent call last):
  File "/home/ub/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 714, in main
    cli.search(args.search_string, nb_results, not args.paid)
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/home/ub/.local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 423, in connect
    gsfid = int(self.gsfid, 16)
ValueError: invalid literal for int() with base 16: 'request'
```

**Comment by eighthave** [comment]
I'm seeing the exact same thing, did you solve it?

**Comment by eighthave** [comment]
ah, I see: #191
