### ISSUE TITLE
google.protobuf.message.DecodeError: Unexpected end-group tag

### ISSUE THREAD

**Issue by aloksaurabh** [matlink/gplaycli#198]
- [ ] Operating System - Kali latest(Linux kali 4.14.0-kali3-686-pae #1 SMP Debian 4.14.12-2kali2 (2018-01-11) i686 GNU/Linux)
- [ ] Python version when running `gplaycli` Python3.6.4
- [ ] GPlayCli version  GPlayCli version 3.24 
- [ ] The way Iinstalled `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`,  Tried both pip and gitclone. Same error in both. 
- [ ] The authentication method: (own) credentials and default conf file provided in the gitclone

The known hotfix suggested in older issue threads to delete the token does not work. Error occurs only during download(both from file and appid). Search works as expected. 

[INFO] GPlayCli version 3.24 [Python3.6.4] 
[INFO] Configuration file is ['gplaycli/gplaycli/gplaycli.conf']
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token: kgZ4rN2zfJYQrtPNS8Qznecpvh[partially_removed]qcGmHiUgcjOQwPQA.
[INFO] GSFId: 36eb[partially_removed]e6d
[INFO] Using auto retrieved token to connect to API
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/gplaycli.py", line 722, in main
    cli.download(args.packages_to_download)
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/gplaycli.py", line 222, in download
    detail = self.api.details(pkg[0])
  File "/usr/local/lib/python3.6/dist-packages/gpapi/googleplay.py", line 394, in details
    data = self.executeRequestApi2(path)
  File "/usr/local/lib/python3.6/dist-packages/gpapi/googleplay.py", line 320, in executeRequestApi2
    message = googleplay_pb2.ResponseWrapper.FromString(response.content)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/python_message.py", line 757, in FromString
    message.MergeFromString(s)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/python_message.py", line 1086, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by matlink** [comment]
Yeah I guess I should check the google accounts used to dispense tokens ...
