### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by ofskymohsen** [matlink/gplaycli#201]
Operating system = ubuntu 16.04
python version = 3.5.2
gplaycli version = 3.25
the way I installed = pip3 install gplaycli and installing dependencies
authentication method = token

I have a folder and in my folder there are a number of .apk files . I want to update these apks . I ran this command : 
`gplaycli --verbose --update .`

but it gives this error :

> [INFO] GPlayCli version 3.25 [Python3.5.2] 
[INFO] Configuration file is gplaycli.conf
[INFO] Device is bacon
[INFO] Using cached token.
[INFO] Checking apks ...
[INFO] Using auto retrieved token to connect to API
[INFO] Analyzing ./Aqua.apk
[INFO] Analyzing ./Compass.apk
[INFO] Analyzing ./ES-file-manager.apk
[INFO] Analyzing ./com.adobe.reader.apk
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 9, in <module>
    load_entry_point('GPlayCli==3.25', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 723, in main
    cli.prepare_analyse_apks()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 516, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, download_folder)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 534, in analyse_local_apks
    apk = APK(filepath)
  File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/core.py", line 16, in __init__
    self.zip_file = get_zip_file(apk)
  File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/utils.py", line 32, in get_zip_file
    return ZipFile(resource)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by ofskymohsen** [comment]
Operating system = ubuntu 16.04
python version = 3.5.2
gplaycli version = 3.25
the way I installed = pip3 install gplaycli and installing dependencies
authentication method = token

I have a folder and in my folder there are a number of .apk files . I want to update these apks . I ran this command : 
`gplaycli --update .`

but it gives this error :
`[INFO] GPlayCli version 3.25 [Python3.5.2] 
[INFO] Configuration file is gplaycli.conf
[INFO] Device is bacon
[INFO] Using cached token.
[INFO] Checking apks ...
[INFO] Using auto retrieved token to connect to API
[INFO] Analyzing ./Aqua.apk
[INFO] Analyzing ./Compass.apk
[INFO] Analyzing ./ES-file-manager.apk
[INFO] Analyzing ./com.adobe.reader.apk
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 9, in <module>
    load_entry_point('GPlayCli==3.25', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 723, in main
    cli.prepare_analyse_apks()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 516, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, download_folder)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 534, in analyse_local_apks
    apk = APK(filepath)
  File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/core.py", line 16, in __init__
    self.zip_file = get_zip_file(apk)
  File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/utils.py", line 32, in get_zip_file
    return ZipFile(resource)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
`

**Comment by matlink** [comment]
Looks like `./com.adobe.reader.apk` is not a zip file. Are you able to extract it manually?

**Comment by ofskymohsen** [comment]
Yes. You are right. I rename com.adobe.reader.apk to .zip file and I am not able to extract it manually. It is corrupted.
