### ISSUE TITLE
Why does it take frequent Google empowerment to re-login to a new device or application?

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#219]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [Windows ] Operating System (ie Ubuntu 16.04)
- [python3+] Python version when running `gplaycli` (should be 3+)
- [3.25 ] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ ] The authentication method: (own) credentials or (own) token.
When I downloaded several apps, I had to re-empower my account. Why?
Error reporting information

Traceback (most recent call last):
  File "/usr/local/anaconda2/envs/python3/bin/gplaycli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda2/envs/python3/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 743, in main
    cli.search(args.search_string, nb_results, not args.paid)
  File "/usr/local/anaconda2/envs/python3/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/usr/local/anaconda2/envs/python3/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 447, in connect
    self.api.login(email=email,password=password,authSubToken=authsub_token,gsfId=gsfid)
  File "/usr/local/anaconda2/envs/python3/lib/python3.6/site-packages/gpapi/googleplay.py", line 227, in login
    raise SecurityCheckError()
gpapi.googleplay.SecurityCheckError

**Comment by matlink** [comment]
It is a protection mechanism from Google to prevent bots and account stealing. If you need to do a lot of requests, create an application password from your Google account and use it in gplaycli.
