### ISSUE TITLE
UnboundLocalError: local variable 'password' referenced before assignment

### ISSUE THREAD

**Issue by blshkv** [matlink/gplaycli#241]
app-misc/gplaycli-3.27
dev-python/gpapi-0.4.4-r1

```
bash$ gplaycli -s whatsapp
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/gplaycli", line 11, in <module>
    load_entry_point('gplaycli==3.27', 'console_scripts', 'gplaycli')()
  File "/usr/lib64/python3.6/site-packages/gplaycli/gplaycli.py", line 628, in main
    cli.search(args.search, not args.paid)
  File "/usr/lib64/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/usr/lib64/python3.6/site-packages/gplaycli/gplaycli.py", line 400, in connect
    return self.connect_credentials()
  File "/usr/lib64/python3.6/site-packages/gplaycli/gplaycli.py", line 426, in connect_credentials
    self.api.login(email=self.gmail_address, password=password)
UnboundLocalError: local variable 'password' referenced before assignment

```

**Comment by anonproject** [comment]
Well, the error you are encountering is because you haven't provided any credentials in the config of gplaycli and because no keyring service is available as well.  You can look that up in the code.

One can try to use keyring service by installing a package keyring (?) and changing token=True in the config.  But it will not work since the IP is blacklisted at Google.  You might try tonuse your own credentials, but Google requires captcha and there is no way to enter it.
So I can't find any solution.  The software simply doesn't work at this point.

**Comment by anonproject** [comment]
Update.  I was able to install android emulator, configure google play and pull the apk out of there.

**Comment by matlink** [comment]
Fixed in master.
