### ISSUE TITLE
server says: BadAuthentication'

### ISSUE THREAD

**Issue by mfrattola** [matlink/gplaycli#260]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ ] Operating System **Debian 10.4**
- [ ] Python version when running `gplaycli` **Python3.7.3**
- [ ] GPlayCli version via `gplaycli -v` **GPlayCli version 3.29**
- [ ] The way you installed `gplaycli`: **python3 -m pip install gplaycli --user**
- [ ] The authentication method: **(own) credentials** 

this is the on-screen log of the session:

../.local/bin/gplaycli -s firefox -c config.ae -v

[INFO] GPlayCli version 3.29 [Python3.7.3]
[INFO] Configuration file is ['config.ae']
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[ERROR] Bad authentication, login or password incorrect ('server says: BadAuthentication')

--------------
config file:

[Credentials]
token=false
gmail_address=ae.xxxxxxxx@google.com
gmail_password=xxxxxxxxxx

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
timezone=CEST

------------

I verified the credentials. If you need anything else, just let me know. Thank you.

**Comment by sharifStrudent** [comment]
I faced same error on other repository today:
[](https://github.com/dweinstein/node-google-play/issues/123)

**Comment by mfrattola** [comment]
Same error with raccon

**Comment by m5x** [comment]
Getting this error as well.

**Comment by keyofd** [comment]
Getting this error as well.

**Comment by jr3074** [comment]
same error today

**Comment by navarasu** [comment]
I am getting this error in the Ubuntu and the Debian machine. It is working on my mac. Is it related to OS libraries?

**Comment by Dibbyo456** [comment]
any fix?

**Comment by mfrattola** [comment]
Hi,


I haven't had the time to check it, but thank you for working on it.

**Comment by sepo83** [comment]
I might have found something...

On a fresh install (alpine; pyhton3.8) I have the same error as mentioned above. `pip3 install gplaycli ` shows:
````
Requirement already satisfied: gplaycli in /gplaycli (3.29)
Requirement already satisfied: matlink-gpapi>=0.4.4.4 in /usr/lib/python3.8/site-packages (from gplaycli) (0.4.4.5)
Requirement already satisfied: pyaxmlparser in /usr/lib/python3.8/site-packages (from gplaycli) (0.3.24)
Requirement already satisfied: protobuf>=3.5.2 in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (3.14.0)
Requirement already satisfied: cryptography>=2.2 in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (3.3.2)
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (2.25.1)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.8/site-packages (from cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (1.15.0)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.8/site-packages (from cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (1.14.4)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (2.20)
Requirement already satisfied: click>=6.7 in /usr/lib/python3.8/site-packages (from pyaxmlparser->gplaycli) (7.1.2)
Requirement already satisfied: lxml in /usr/lib/python3.8/site-packages (from pyaxmlparser->gplaycli) (4.6.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (4.0.0)
Requirement already satisfied: idna<3.2,>=2.5 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (1.26.2)
````

When I downgrade  urllib3 with `pip3 install --upgrade urllib3==1.24.2`, the plaintext password works.

**Comment by gentoolinux** [comment]
> When I downgrade urllib3 with `pip3 install --upgrade urllib3==1.24.2`, the plaintext password works.

Awesome! After downgrading urllib3 from 1.26.2 to 1.25.11 gplaycli is working for me again, too.

Thanks to your hint, I have found this issue: https://github.com/urllib3/urllib3/issues/2101
Obviously the issue can be fixed by adjusting the supported cipher suites.
I did not had time to check how to apply this to gplaycli.

**Comment by BiatuAutMiahn** [comment]
Confirmed

**Comment by shalva97** [comment]
same here, no matter what it always says `[ERROR] Bad authentication, login or password incorrect ('server says: BadAuthentication')`

**Comment by fontanon** [comment]
> I might have found something...
> 
> On a fresh install (alpine; pyhton3.8) I have the same error as mentioned above. `pip3 install gplaycli ` shows:
> 
> ```
> Requirement already satisfied: gplaycli in /gplaycli (3.29)
> Requirement already satisfied: matlink-gpapi>=0.4.4.4 in /usr/lib/python3.8/site-packages (from gplaycli) (0.4.4.5)
> Requirement already satisfied: pyaxmlparser in /usr/lib/python3.8/site-packages (from gplaycli) (0.3.24)
> Requirement already satisfied: protobuf>=3.5.2 in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (3.14.0)
> Requirement already satisfied: cryptography>=2.2 in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (3.3.2)
> Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (from matlink-gpapi>=0.4.4.4->gplaycli) (2.25.1)
> Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.8/site-packages (from cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (1.15.0)
> Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.8/site-packages (from cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (1.14.4)
> Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.2->matlink-gpapi>=0.4.4.4->gplaycli) (2.20)
> Requirement already satisfied: click>=6.7 in /usr/lib/python3.8/site-packages (from pyaxmlparser->gplaycli) (7.1.2)
> Requirement already satisfied: lxml in /usr/lib/python3.8/site-packages (from pyaxmlparser->gplaycli) (4.6.2)
> Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (4.0.0)
> Requirement already satisfied: idna<3.2,>=2.5 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (3.1)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->matlink-gpapi>=0.4.4.4->gplaycli) (1.26.2)
> ```
> 
> When I downgrade urllib3 with `pip3 install --upgrade urllib3==1.24.2`, the plaintext password works.

This worked for me.

**Comment by gentoolinux** [comment]
Finally I managed to take a deeper look at this issue.
The issue can not be fixed in gplaycli. It needs to be fixed in googleplay-api.
I was able to resolve the issue using to following (quick and dirty) patch: https://github.com/gentoolinux/googleplay-api/commit/6e4c7a47b59f2a1a512b05380127f87369e308ff

**Comment by onny** [comment]
> Finally I managed to take a deeper look at this issue.
> The issue can not be fixed in gplaycli. It needs to be fixed in googleplay-api.
> I was able to resolve the issue using to following (quick and dirty) patch: [gentoolinux/googleplay-api@6e4c7a4](https://github.com/gentoolinux/googleplay-api/commit/6e4c7a47b59f2a1a512b05380127f87369e308ff)

Have you opened a pull request? Thanks for your work!

**Comment by matlink** [comment]
Thank you for investingating it. I could pin the urllib version as a temporary fix.

**Comment by sudofox** [comment]
> I could[...]

How are we doing here? I'm trying to write a utility to automatically generate diffs between app versions when a new one is released.

**Comment by 89z** [comment]
Fix didnt work for me, I get:

Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password

**Comment by 89z** [comment]
I have an alternate tool/module that works:

~~~
PS C:\> googleplay -a com.google.android.youtube
&{DocV2:{Details:{AppDetails:{DeveloperName:Google LLC VersionCode:1524094400
Version:16.43.34 InstallationSize:34674581 UploadDate:Oct 27, 2021}}}}
~~~

https://github.com/89z/googleplay

**Comment by besendorf** [comment]
Is there any news on this issue? This has already lead other projects like exodus to maintain their own version of gplayapi: https://github.com/Exodus-Privacy/exodus/commit/685ae5cf0a34c2cd6ed428a895b39cab39957224

**Comment by besendorf** [comment]
I forked the projected and the library used by it. I also uploaded it to pypi. You can check it out [here](https://github.com/besendorf/gplaycli) or just do `pip install gplaycli2`

**Comment by muzzyrost** [comment]
Same issue again on both login types with MFA and without it.

```
gplaycli -v -s youtube
[INFO] GPlayCli version 3.29 [Python3.9.5]
[INFO] Configuration file is /home/ub/.local/etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
Traceback (most recent call last):
  File "/home/ub/.local/bin/gplaycli", line 8, in <module>
    sys.exit(main())
  File "/home/ub/.local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 651, in main
    cli.search(args.search, not args.paid)
  File "/home/ub/.local/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/home/ub/.local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 415, in connect
    ok, err = self.connect_credentials()
  File "/home/ub/.local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 448, in connect_credentials
    self.api.login(email=self.gmail_address, password=password)
  File "/home/ub/.local/lib/python3.9/site-packages/gpapi/googleplay.py", line 262, in login
    raise SecurityCheckError("Security check is needed, try to visit "
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'
```

**Comment by aerickson** [comment]
@besendorf is your fork still working for you? Getting 'bad authentication' even when using an app password. Thanks!

**Comment by besendorf** [comment]
> @besendorf is your fork still working for you? Getting 'bad authentication' even when using an app password. Thanks!

Unfortunatly not but this still works for me:
https://github.com/89z/googleplay
however it's not as easy to use

**Comment by IamDopey** [comment]
Using https://github.com/89z/googleplay gives me "uploadDate not found, try another platform" error message. @besendorf

**Comment by 89z** [comment]
@IamDopey please don't ask other people for help with my software. If you do so again, or if @besendorf replies to your comment here, I will revoke your license to my software. I would suggest you remove your comment.

**Comment by MC874** [comment]
The repository is gone, do You have backup or alternatives? @besendorf

**Comment by 9hk** [comment]
its moved here for now: https://github.com/9hk/googleplay

**Comment by MC874** [comment]
Thanks, will try @9hk

**Comment by TheOppaiDragon** [comment]
> I forked the projected and the library used by it. I also uploaded it to pypi. You can check it out [here](https://github.com/besendorf/gplaycli) or just do `pip install gplaycli2`

I tried to clone your repo, setting my account google and when i try to do: `gplaycli -s name app`  i got this error
![image](https://github.com/user-attachments/assets/e38de978-a5b1-4208-96ae-ee04fc55e724)

**Comment by 3052** [comment]
@TheOppaiDragon I have tool:

~~~
> play -i jp.kadokawa.gab.rezero_witch -b  arm64-v8a
06:13:30 INFO POST URL=https://android.googleapis.com/auth
06:13:30 INFO GET URL="https://android.clients.google.com/fdfe/details?doc=jp.kadokawa.gab.rezero_witch"
details[8] = 0 USD
details[13][1][4] = 1.0.1
details[13][1][12] = https://re-zero-witch.jp/
details[13][1][16] = Aug 20, 2024
details[13][1][17] = APK APK APK
details[13][1][82][1][1] = 11 and up
downloads = 17.20 thousand
name = Ｒｅ：ゼロから始める異世界生活 ウィッチズリザレクション
size = 293.47 megabyte
version code = 11
~~~

**Comment by 3052** [comment]
https://github.com/3052/google

**Comment by TheOppaiDragon** [comment]
> https://github.com/3052/google

how can i install and use that?

**Comment by 3052** [comment]
@TheOppaiDragon post an issue to my repo or contact me privately

**Comment by TheOppaiDragon** [comment]
> @TheOppaiDragon post an issue to my repo or contact me privately

how i contact u privately?

**Comment by 3052** [comment]
check my god damn profile, jesus christ

**Comment by TheOppaiDragon** [comment]
> check my god damn profile, jesus christ

sorry i sent u request on discord
