### ISSUE TITLE
Error while retrieving information from server. DF-DFERH-01

### ISSUE THREAD

**Issue by lamanux** [matlink/gplaycli#271]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ ] Operating System (ie Ubuntu 16.04)
$ uname -a
Linux ME01 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
- [ ] Python version when running `gplaycli` (should be 3+)
Python3.7.3
- [ ] GPlayCli version via `gplaycli -v`
$gplaycli -v
[INFO] GPlayCli version 3.29 [Python3.7.3]
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
apt install gplaycli
- [ ] The authentication method: (own) credentials or (own) token.
(own) credentials

- When I try to download an app:

$ gplaycli -v -d com.appxy.tinyscanner.apk
[INFO] GPlayCli version 3.29 [Python3.7.3]
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[ERROR] A few packages could not be downloaded :
com.appxy.tinyscanner.apk
'Error while retrieving information from server. DF-DFERH-01'

- When I try to update app in the directory:

$ gplaycli -u ./
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 11, in <module>
    load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 653, in main
    cli.prepare_analyse_apks()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 505, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, self.download_folder)
  File "/usr/lib/python3/dist-packages/gplaycli/hooks.py", line 11, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 530, in analyse_local_apks
    details = self.api.bulkDetails(package_bunch)
  File "/usr/lib/python3/dist-packages/gpapi/googleplay.py", line 399, in bulkDetails
    params=params)
  File "/usr/lib/python3/dist-packages/gpapi/googleplay.py", line 336, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error while retrieving information from server. DF-DFERH-01'

**Comment by cweiske** [comment]
Downloads via tokens work, but this here happens only when using username+password.

**Comment by lamanux** [comment]
> Downloads via tokens work, ...

Not for me. With tokens default configuration, i get  a error commented in this issue #263.

**Comment by cweiske** [comment]
I have the same issue with the default token server, but I used the Token Dispenser used by Aurora Store app - that one works.

**Comment by ford--prefect** [comment]
I can confirm this issue with python 3.8.6 on Archlinux, gplaycli installed from the AUR in version 3.29.
The error occurs both with own credentials and with the standard token dispenser.

**Comment by ford--prefect** [comment]
FWIW: this error does only occur in the --update mode, not in -d mode.

**Comment by cweiske** [comment]
Also happens here with -d mode.

**Comment by fernandocollova** [comment]
Hi everyone! So, as you might guess, I'm experiencing this exact same problem, but I'm experiencing it in a small docker container I put together to download some gplay apps. It's not very well put together, but I'm going to leave [here](https://bitbucket.org/fernandocollova/repomaker/src/master/) in case it can be used to provide an env where the issue is reproducible

Finally, I think the only missing piece of the puzzle to get that to work is the gplaycli.conf file, which I provide below (redacted of course):

`[Credentials]
gmail_address=the_email
gmail_password=the_password
token=False

[Locale]
locale=es_AR
timezone=America/Argentina/Buenos_Aires

[Device]
codename=polaris`

Happy to provide any more info if needed, or debugging, or test fixes. I also might be looking into this issue in more detail in the near future, but I'm not familiar at all with the google play api, so I might not get to nothing.

Thanks, Fernando

**Comment by fernandocollova** [comment]
Ok, so, this is the progress I have so far:

- I traced the error back to here: https://github.com/matlink/googleplay-api/blob/7ddd176c73197b858b3e90a93e0e1a9e0875bdc7/gpapi/googleplay.py#L626
- While I was trying to test some random stuff like compiling my own protocol buffers (because the error is 2 lines after some protobuff stuff, and I didn't know what else to try) I noticed that I always got `Bad authentication, login or password incorrect ('server says: BadAuthentication')` when deploying the code from source. Latest tag available on git is 0.4.4.4, and the pypi version is 0.4.4.5, so maybe its that, but I don't have much more time to test right now.

Having said that, I'm not quite sure what to test next. Does that line give you any clue of what mught be wrong? Maybe some device specific problem? Maybe the locale?

I realized I never posted a traceback of the error before, so here it goes in case it helps

Thanks, Fernando

```
[INFO] 2 / 2 com.spotify.music
[ERROR] Error while downloading com.spotify.music
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gplaycli/gplaycli.py", line 269, in download
    data_iter = method(packagename, expansion_files=self.addfiles_enable)
  File "/usr/local/lib/python3.7/dist-packages/gpapi/googleplay.py", line 626, in download
    raise RequestError(response.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Se produjo un error cuando se recuperaba la información del servidor ([DF-DFERH-01]).'
[ERROR] A few packages could not be downloaded :
com.spotify.music
'Se produjo un error cuando se recuperaba la información del servidor ([DF-DFERH-01]).'
```

**Comment by Apfelwurm** [comment]
I also had authentication problems with user and password and i got it fixed by installing v 1.24.2 of urllib3 and the version from pip.
It was mentioned in an other issue here but i cant find it at the moment.

`python3 -m pip install gplaycli && python3 -m pip install --upgrade urllib3==1.24.2`

i also was not able to download with the default device and i had to use 
`gplaycli --device-codename oneplus3 -d APPNAME
 gplaycli --device-codename bacon -d APPNAME
gplaycli --device-codename bullhead -d APPNAME`

depending on the app.

**Comment by fernandocollova** [comment]
Thanks for the suggestion! Now auth works with the git version, which means I can debug more easily. Now the question is, what do I test :joy: but this is a step forward

**Comment by d78ui98** [comment]
Hello everyone. I am facing the same issue.
Did anyone find any solution or any workaround?
cc- @matlink @fernandocollova

**Comment by fernandocollova** [comment]
Unfortunately, no. I don't know nearly enough about google play's API to debug the issue, and as far as I remember this was a "the API didn't return what I need" type of issue. I am happy to help on the python side of things, but unfortunately, I don't have time to research what the expected API behavior is :/

**Comment by fernandocollova** [comment]
@d78ui98 Something you might be interested on, is this other app: https://github.com/ClaudiuGeorgiu/PlaystoreDownloader which can actually download packages! Or at least it can download Spotify :sweat_smile:

**Comment by d78ui98** [comment]
Thanks @fernandocollova I will check this one out :)

**Comment by 89z** [comment]
https://github.com/rehmatworks/gplaydl/issues/27

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
googleplay -a com.bandcamp.android -v 216343
~~~

https://github.com/89z/googleplay

**Comment by NTT1906** [comment]
> I have an alternate tool that works:
> 
> ```
> googleplay -a com.bandcamp.android -v 216343
> ```
> 
> https://github.com/89z/googleplay

did you make it?

**Comment by 89z** [comment]
Yes

**Comment by BrunoFischerGermany** [comment]
I use `glpaycli -v` the result is `3.29 [Python3.8.10]`
Now i have an issuse. 

the result is
> `[INFO] GPlayCli version 3.29 [Python3.8.10]`
> `[INFO] Configuration file is ['/home/anwender/gplaycli.conf']`
> `[INFO] Device is bacon`
> `[INFO] Using credentials to connect to API`
> `[INFO] Using plaintext password`
> `[INFO] 1 / 1 com.miui.weather2`
> `/home/anwender/.local/lib/python3.8/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted`
> `  response = googleplay_pb2.ResponseWrapper.FromString(response.content)`
> `[ERROR] Error while downloading com.miui.weather2 : 'Fehler beim Abrufen von Informationen vom Server: DF-DFERH-01'`
> `[ERROR] A few packages could not be downloaded :`
> `com.miui.weather2`
> `'Fehler beim Abrufen von Informationen vom Server: DF-DFERH-01'`

i don't know the problem. :'(
The Line 'Fehler beim Abrufen von Informationen vom Server: DF-DFERH-01' is in english ''Error while retrieving information from server. DF-DFERH-01'

Can anyone help?

thanks

**Comment by 89z** [comment]
https://github.com/matlink/gplaycli/issues/289
