### ISSUE TITLE
googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted

### ISSUE THREAD

**Issue by acim** [matlink/gplaycli#272]
- [x] Operating System Linux Mint 20 Ulyana
- [x] Python version 3.8.2
- [x] GPlayCli version 3.29
- [x] The way you installed `gplaycli`: `pip install gplaycli`
- [x] The authentication method: (own) credentials

Applications get downloaded but I get the following error:

```
/home/xxx/.local/lib/python3.8/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
```

**Comment by guoqiao** [comment]
My error:
```
[ERROR] Error while downloading com.pushbullet.android : Unexpected end-group tag.
[ERROR] A few packages could not be downloaded :
com.pushbullet.android
Unexpected end-group tag.
```

**Comment by Yuubari** [comment]
This seems like the same problem as in NoMore201/googleplay-api#132. I tried the suggested fix and it seems to be working for me.

**Comment by guoqiao** [comment]
verbose log:
```
gplaycli --verbose --progress -d $APK
[INFO] GPlayCli version 3.29 [Python3.8.2] 
[INFO] Configuration file is /home/guoqiao/git/gplaycli/gplaycli.conf
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[INFO] 1 / 1 com.pushbullet.android
/usr/local/lib/python3.8/dist-packages/gpapi/googleplay.py:634: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('gplaycli', 'console_scripts', 'gplaycli')()
  File "/home/guoqiao/git/gplaycli/gplaycli/gplaycli.py", line 659, in main
    cli.download(args.download)
  File "/home/guoqiao/git/gplaycli/gplaycli/hooks.py", line 11, in check_connection
    return function(self, *args, **kwargs)
  File "/home/guoqiao/git/gplaycli/gplaycli/gplaycli.py", line 290, in download
    splits = data_iter['splits']
KeyError: 'splits'
```

**Comment by guoqiao** [comment]
Created a PR to fix this. Review and Merge appreciated !

**Comment by shtrom** [comment]
Still getting the error with @guoqiao's fix

```[21:42:48] @supahwinch ~/src/gplaycli$ git describe                                                    130 ↵  [gplaycli] (remotes/gh-guoqiao/Issue-272-splits-keyerror)
fatal: No annotated tags can describe '711d64fad285272543c619fd1152efa3d39a2626'.
However, there were unannotated tags: try --tags.
[21:42:50] @supahwinch ~/src/gplaycli$ gplaycli --verbose --progress -d  au.gov.tas.checkin         0s 128 ↵  [gplaycli] (remotes/gh-guoqiao/Issue-272-splits-keyerror)
[INFO] GPlayCli version 3.29 [Python3.9.2] 
[INFO] Configuration file is /home/shtrom/src/gplaycli/gplaycli.conf
[INFO] Device is bacon
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
[INFO] 1 / 1 au.gov.tas.checkin
/home/shtrom/src/gplaycli/.venv/gplaycli/lib/python3.9/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
[ERROR] Error while downloading au.gov.tas.checkin : 'Error while retrieving information from server. [DF-DFERH-01]'
[ERROR] A few packages could not be downloaded :
au.gov.tas.checkin
'Error while retrieving information from server. [DF-DFERH-01]'

```
