### ISSUE TITLE
Permission denied: 'token.cache'

### ISSUE THREAD

**Issue by nobicycle** [matlink/gplaycli#281]
- [ ] Operating System (ie Ubuntu 16.04)
 uname -a
Linux tower 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux

- [ ] Python version when running `gplaycli` (should be 3+)
$ python -V
Python 3.9.5

- [ ] GPlayCli version via `gplaycli -v`
$ gplaycli -v
[INFO] GPlayCli version 3.29 [Python3.9.5] 
[INFO] Configuration file is /home/user/.local/etc/gplaycli/gplaycli.conf
[INFO] Device is bacon

- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

pip install

- [ ] The authentication method: (own) credentials or (own) token.
token

$ gplaycli -v -t  -tu https://matlink.fr/token -f ~/tmp -av -a -p -L -s freshrss
[INFO] GPlayCli version 3.29 [Python3.9.5] 
[INFO] Configuration file is /home/user/.local/etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
[Errno 2] No such file or directory: 'token.cache'
[INFO] Cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token
[INFO] Email: gplaycli3@gmail.com
[INFO] Token: <removed>
[INFO] GsfId: <removed>
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 651, in main
    cli.search(args.search, not args.paid)
  File "/usr/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 412, in connect
    self.retrieve_token()
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 204, in retrieve_token
    self.write_cached_token(self.token, self.gsfid, self.gmail_address)
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 485, in write_cached_token
    with open(self.tokencachefile, 'w') as tcf:
PermissionError: [Errno 13] Permission denied: 'token.cache'
[user@tower rapidlauncher]$ gplaycli -v -t  -tu goolag.store:1337 -f ~/tmp -av -a -p -L -s freshrss

<removed> means I edited the output and removed it in these cases

**Comment by matlink** [comment]
It looks like you are in an unwritable directory or that your user cannot write the token cache file. 

Le 29 juin 2021 04:28:23 GMT+02:00, nobicycle ***@***.***> a écrit :
>- [ ] Operating System (ie Ubuntu 16.04)
> uname -a
>Linux tower 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC
>2021 x86_64 GNU/Linux
>
>- [ ] Python version when running `gplaycli` (should be 3+)
>$ python -V
>Python 3.9.5
>
>- [ ] GPlayCli version via `gplaycli -v`
>$ gplaycli -v
>[INFO] GPlayCli version 3.29 [Python3.9.5] 
>[INFO] Configuration file is
>/home/user/.local/etc/gplaycli/gplaycli.conf
>[INFO] Device is bacon
>
>- [ ] The way you installed `gplaycli`: `git clone`, `git clone and
>setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
>
>pip install
>
>- [ ] The authentication method: (own) credentials or (own) token.
>token
>
>$ gplaycli -v -t  -tu https://matlink.fr/token -f ~/tmp -av -a -p -L -s
>freshrss
>[INFO] GPlayCli version 3.29 [Python3.9.5] 
>[INFO] Configuration file is
>/home/user/.local/etc/gplaycli/gplaycli.conf
>[INFO] Device is bacon
>[Errno 2] No such file or directory: 'token.cache'
>[INFO] Cache file does not exists or is corrupted
>[INFO] Retrieving token ...
>[INFO] Token URL is https://matlink.fr/token
>[INFO] Email: ***@***.***
>[INFO] Token: <removed>
>[INFO] GsfId: <removed>
>Traceback (most recent call last):
>  File "/usr/bin/gplaycli", line 33, in <module>
>sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts',
>'gplaycli')())
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 651,
>in main
>    cli.search(args.search, not args.paid)
>File "/usr/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in
>check_connection
>    ok, err = self.connect()
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 412,
>in connect
>    self.retrieve_token()
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 204,
>in retrieve_token
>    self.write_cached_token(self.token, self.gsfid, self.gmail_address)
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 485,
>in write_cached_token
>    with open(self.tokencachefile, 'w') as tcf:
>PermissionError: [Errno 13] Permission denied: 'token.cache'
***@***.*** rapidlauncher]$ gplaycli -v -t  -tu goolag.store:1337 -f
>~/tmp -av -a -p -L -s freshrss
>
><removed> means I edited the output and removed it in these cases
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/281

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
