### ISSUE TITLE
Unable to configure gplycli on my Mac. Facing the below mentioned issue

### ISSUE THREAD

**Issue by jain6196** [matlink/gplaycli#282]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ ] Operating System: Mac OS Big Sur
- [ ] Python version when running `gplaycli` : Python 3.9.5
- [ ] GPlayCli version via `gplaycli -v` GPlayCli version 3.29
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, : pip installl
- [ ] The authentication method: (own) credentials or (own) token : own credentials

[WARNING] No configuration file gplaycli.conf found at ['/Users/sj/Documents/NewTools/gplaycli/gplaycli', '/Users/sj/Library/Python/3.9/etc/gplaycli', '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/local/etc/gplaycli', '/etc/gplaycli'], using default values
[Errno 2] No such file or directory: 'token.cache'
[ERROR] Cannot retrieve email address from token dispenser
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 659, in main
    cli.download(args.download)
  File "/usr/local/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 412, in connect
    self.retrieve_token()
  File "/usr/local/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 193, in retrieve_token
    raise ERRORS.TOKEN_DISPENSER_SERVER_ERROR

**Comment by jain6196** [comment]
I was able to configure but getting this error now. My Laptop configuration and gplaycli configurations are same.

gplaycli -v
[INFO] GPlayCli version 3.29 [Python3.9.5] 
[INFO] Configuration file is /usr/local/etc/gplaycli/gplaycli.conf
[INFO] Device is bacon

/usr/local/lib/python3.9/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
[ERROR] Error while downloading hpandro.java.infosec.backdooor1 : 'Error while retrieving information from server. [DF-DFERH-01]'
[ERROR] A few packages could not be downloaded :
hpandro.java.infosec.backdooor1
'Error while retrieving information from server. [DF-DFERH-01]'

**Comment by Seegras** [comment]
Same on Linux, Debian/sid

gplaycli -v 
[INFO] GPlayCli version 3.29 [Python3.9.2] 
[INFO] Configuration file is /home/user/gplaycli.conf
[INFO] Device is bacon

/usr/lib/python3/dist-packages/gpapi/googleplay.py:643: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
[ERROR] Error while downloading tk.hack5.treblecheck : 'Error while retrieving information from server. DF-DFERH-01'
[ERROR] A few packages could not be downloaded :

Chaning the token dispenser to aurora_oss http://auroraoss.com:8080 doesn't change anything; 
setting auth to user also doesn't work, apparently google changed their auth-system again in june 2021.
