### ISSUE TITLE
[ERROR] Cannot retrieve email address from token dispenser

### ISSUE THREAD

**Issue by 89z** [matlink/gplaycli#283]
~~~
PS C:\> gplaycli -d com.google.android.youtube
[WARNING] No configuration file gplaycli.conf found at ['D:\\Desktop',
'C:\\Users\\Steven\\AppData\\Roaming\\Python\\etc\\gplaycli',
'C:\\python\\local\\etc\\gplaycli', '/etc\\gplaycli'], using default values
[Errno 2] No such file or directory: 'token.cache'
[ERROR] Cannot retrieve email address from token dispenser
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\python\Scripts\gplaycli.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\gplaycli\gplaycli.py", line 659, in main
    cli.download(args.download)
  File "C:\python\lib\site-packages\gplaycli\hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "C:\python\lib\site-packages\gplaycli\gplaycli.py", line 412, in connect
    self.retrieve_token()
  File "C:\python\lib\site-packages\gplaycli\gplaycli.py", line 193, in retrieve_token
    raise ERRORS.TOKEN_DISPENSER_SERVER_ERROR
TypeError: exceptions must derive from BaseException
~~~

**Comment by matlink** [comment]
Google may have blacklisted my IP so I can't use google accounts from my token dispenser server. I'm quite stuck with this.

**Comment by oldmud0** [comment]
@matlink does Google block EC2 IP ranges (or even their own GCP IP ranges)? Maybe you might have some more luck moving the token dispenser to the public cloud.

**Comment by 89z** [comment]
Alternative:

http://goolag.store:1337/api/auth

**Comment by oldmud0** [comment]
Okay, well, that's one way to do it :smirk:

**Comment by 89z** [comment]
@oldmud0 yeah sadly, most of the current Google Play options are pretty bad. Unfortunately, that includes this repo as well.
