### ISSUE TITLE
Don't understand error - CentOS 7

### ISSUE THREAD

**Issue by dark159123** [matlink/gplaycli#37]
Whether i search for an app or try to download one, i get this error

```
$ gplaycli -s protonmail
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 366, in <module>
    main()
  File "/usr/bin/gplaycli", line 340, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/bin/gplaycli", line 53, in connect_to_googleplay_api
    api.login(self.config["gmail_address"], self.config["gmail_password"], None)
  File "/usr/lib/python2.7/site-packages/ext_libs/googleplay_api/googleplay.py", line 126, in login
    response = requests.post(self.URL_LOGIN, data=params, headers=headers, verify=ssl_verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 325, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```
setenforce 0 doesn't help, and firewalld is also disabled.
I am using the standard credentials.conf.

**Comment by matlink** [comment]
Which version of python are you using ?

**Comment by matlink** [comment]
Sounds like an BaseSSLError (http://bugs.python.org/issue10272). Can you try to upgrade your dependencies (via pip for example) ?

**Comment by dark159123** [comment]
After running `pip install --upgrade requests protobuf ndg-httpsclient androguard clint pyasn1` which finishes without errors i run:
`# gplaycli -s protonmail

Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 366, in <module>
    main()
  File "/usr/bin/gplaycli", line 340, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/bin/gplaycli", line 53, in connect_to_googleplay_api
    api.login(self.config["gmail_address"], self.config["gmail_password"], None)
  File "/usr/lib/python2.7/site-packages/ext_libs/googleplay_api/googleplay.py", line 126, in login
    response = requests.post(self.URL_LOGIN, data=params, headers=headers, verify=ssl_verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 323, in connect
    ssl_context=context)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 392, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
`

**Comment by matlink** [comment]
OS ?

Le 26 novembre 2016 10:01:12 GMT+01:00, dark159123 <notifications@github.com> a écrit :
>After running `pip install --upgrade requests protobuf ndg-httpsclient
>androguard clint pyasn1` which finishes without errors i run:
>`# gplaycli -s protonmail
>
>Traceback (most recent call last):
>  File "/usr/bin/gplaycli", line 366, in <module>
>    main()
>  File "/usr/bin/gplaycli", line 340, in main
>    success, error = cli.connect_to_googleplay_api()
>  File "/usr/bin/gplaycli", line 53, in connect_to_googleplay_api
>api.login(self.config["gmail_address"], self.config["gmail_password"],
>None)
>File
>"/usr/lib/python2.7/site-packages/ext_libs/googleplay_api/googleplay.py",
>line 126, in login
>response = requests.post(self.URL_LOGIN, data=params, headers=headers,
>verify=ssl_verify)
>File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in
>post
>    return request('post', url, data=data, json=json, **kwargs)
>File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in
>request
>    return session.request(method=method, url=url, **kwargs)
>File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488,
>in request
>    resp = self.send(prep, **send_kwargs)
>File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609,
>in send
>    r = adapter.send(request, **kwargs)
>File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423,
>in send
>    timeout=timeout
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py",
>line 594, in urlopen
>    chunked=chunked)
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py",
>line 350, in _make_request
>    self._validate_conn(conn)
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py",
>line 835, in _validate_conn
>    conn.connect()
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py",
>line 323, in connect
>    ssl_context=context)
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py",
>line 308, in ssl_wrap_socket
>    context.load_verify_locations(ca_certs, ca_cert_dir)
>File
>"/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py",
>line 392, in load_verify_locations
>    self._ctx.load_verify_locations(cafile, capath)
>File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in
>load_verify_locations
>    _raise_current_error()
>File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in
>exception_from_error_queue
>    raise exception_type(errors)
>OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or
>directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509
>certificate routines', 'X509_load_cert_crl_file', 'system lib')]
>`
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/37#issuecomment-263052506

-- 
Matlink - sysadmin Matlink.fr

**Comment by dark159123** [comment]
CentOS 7.

**Comment by matlink** [comment]
In /usr/lib/python2.7/site-packages/ext_libs/googleplay_api/googleplay.py, what is the value of ssl_verify at the beginning ?

Le 26 novembre 2016 10:04:41 GMT+01:00, dark159123 <notifications@github.com> a écrit :
>CentOS 7.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/37#issuecomment-263052634

-- 
Matlink - sysadmin Matlink.fr

**Comment by dark159123** [comment]
`ssl_verify="/etc/ssl/certs/ca-certificates.crt"`

**Comment by matlink** [comment]
Can you put True without quote instead ?

Le 26 novembre 2016 10:21:53 GMT+01:00, dark159123 <notifications@github.com> a écrit :
>`ssl_verify="/etc/ssl/certs/ca-certificates.crt"`
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/37#issuecomment-263053355

-- 
Matlink - sysadmin Matlink.fr

**Comment by dark159123** [comment]
It works now.
I'm guessing this made it accept any certificate and therefore it shouldn't be used outside testing environments?

**Comment by matlink** [comment]
No, on Debian, we are forced to specify the location of ca bundles, which is not needed on redhat

Le 26 novembre 2016 10:30:37 GMT+01:00, dark159123 <notifications@github.com> a écrit :
>It works now.
>I'm guessing this made it accept any certificate and therefore it
>shouldn't be used outside testing environments?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/37#issuecomment-263053733

-- 
Matlink - sysadmin Matlink.fr

**Comment by dark159123** [comment]
I see. thank you for the help.

**Comment by matlink** [comment]
Could you remove `gplaycli` and install the new version (0.1.5-post2) with pip? It now handles that error.

**Comment by dark159123** [comment]
Both search and download works with the update.
Thank you!

**Comment by ylecuyer** [comment]
I had the same issue with the lastest version installed via pip on macos
