### ISSUE TITLE
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'

### ISSUE THREAD

**Issue by dark159123** [matlink/gplaycli#41]
Running under current debian stable with all dependencies (listed in readme.md and requirements.txt) installed i still get this error when running gplaycli:
```
$ ./gplaycli/gplaycli
Traceback (most recent call last):
  File "./gplaycli/gplaycli", line 24, in <module>
    from ext_libs.googleplay_api.googleplay import GooglePlayAPI  # GooglePlayAPI
  File "/usr/local/lib/python2.7/dist-packages/ext_libs/googleplay_api/googleplay.py", line 14, in <module>
    from OpenSSL.SSL import Error as SSLError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'
```
When running with python3:
```
$ python3 ./gplaycli/gplaycli
  File "./gplaycli/gplaycli", line 56
    except LoginError, exc:
                     ^
SyntaxError: invalid syntax
```
Same result when running gplaycli installed through pip and when cloned from github.
EDIT: Same error when using version 0.1.2.

**Comment by dark159123** [comment]
It works on a fresh install, so it must be caused by some fiddling i did with the python packages out of incompetence.
Feel free to reopen this if you feel like it.
