### ISSUE TITLE
Call gplaycli with php

### ISSUE THREAD

**Issue by mohsennouri** [matlink/gplaycli#44]
Hi
I want run this code:
```
<?php
chdir('/home/user/gplay/');
$result = shell_exec('gplaycli -c credentials1.conf -f dl/ -pvd com.packagename 2>&1');
print_r($result);
```
but this error shows:
```
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 24, in <module>
    from ext_libs.googleplay_api.googleplay import GooglePlayAPI  # GooglePlayAPI
  File "/usr/lib/python2.7/dist-packages/ext_libs/googleplay_api/googleplay.py", line 9, in <module>
    from google.protobuf import descriptor
  File "/usr/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/python2.7/dist-packages/google/protobuf/pyext/_message.x86_64-linux-gnu.so)
```
I can run gplaycli with terminal, but with php NO.
Please help.

**Comment by matlink** [comment]
Sounds like your php shell environment is not the same as your bash environment.
Check this stackoverflow thread http://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by
I guess you need to add to php environment the `LD_LIBRARY_PATH` variable and make it point to your correct `GLIBC` folder.
