### ISSUE TITLE
Could not find a suitable TLS CA 

### ISSUE THREAD

**Issue by 461934404** [matlink/gplaycli#67]
./gplaycli -h
Traceback (most recent call last):
  File "./gplaycli", line 25, in <module>
    from ext_libs.googleplay_api.googleplay import GooglePlayAPI  # GooglePlayAPI
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 23, in <module>
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/adapters.py", line 405, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/adapters.py", line 225, in cert_verify
    "invalid path: {0}".format(cert_loc))
IOError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

**Comment by matlink** [comment]
Could you please post `./gplaycli -v` output?
What's your OS?

**Comment by 461934404** [comment]
./gplaycli -v 
Traceback (most recent call last):
  File "./gplaycli", line 25, in <module>
    from ext_libs.googleplay_api.googleplay import GooglePlayAPI  # GooglePlayAPI
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 23, in <module>
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/adapters.py", line 405, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/python-2.7.7/lib/python2.7/site-packages/requests-2.14.2-py2.7.egg/requests/adapters.py", line 225, in cert_verify
    "invalid path: {0}".format(cert_loc))
IOError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

os : centos 6.8

**Comment by matlink** [comment]
Okay, Centos has no CA bundle to this path. It's a known bug. See https://github.com/matlink/gplaycli/issues/37

**Comment by 461934404** [comment]
Are there any other solutions?

**Comment by matlink** [comment]
In ext_libs/googleplay_api/googleplay.py, what is the value of ssl_verify at the beginning?

**Comment by matlink** [comment]
I've commited a quick patch to ext_libs/googleplay_api/googleplay.py, can you please git pull your repo and try again?

**Comment by 461934404** [comment]
Yes，This problem has been solved, but the download has failed. Please help me again，thank you！

proxychains4 python tests/test_init.py 
Traceback (most recent call last):
  File "tests/test_init.py", line 39, in <module>
    test_download_duckduckgo()
  File "tests/test_init.py", line 36, in test_download_duckduckgo
    gpc.download_packages(['com.zoylo.com'])
  File "/home/yingjun/gplaycli/gplaycli/gplaycli.py", line 346, in download_packages
    self.download_selection(self.playstore_api, [(pkg, None) for pkg in list_of_packages_to_download],
AttributeError: 'GPlaycli' object has no attribute 'playstore_api'

**Comment by matlink** [comment]
What are you trying to do?

**Comment by 461934404** [comment]
Use test_init.py to download an App

**Comment by matlink** [comment]
Well see README.md for usage instructions
