### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xhzhang** [matlink/gplaycli#89]
Please provide those informations:

- [ ] Operating System: centos
- [ ] Python version: python 2.7.5 under virtualenv
- [ ] GPlayCli version: 0.2.8.post1
- [ ] The way you installed `gplaycli`:  `git clone and setup.py`, 

I am using command:  gplaycli -s "facebook", or to download any app: gplaycli -d "com.xda.labs.play"

> Traceback (most recent call last):
  File "/home/xxx/venv/bin/gplaycli", line 4, in <module>
    __import__('pkg_resources').run_script('GPlayCli==0.2.8.post1', 'gplaycli')
  File "/home/xxx/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xxx/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/home/xxx/venv/lib/python2.7/site-packages/GPlayCli-0.2.8.post1-py2.7.egg/EGG-INFO/scripts/gplaycli", line 535, in <module>
  File "/home/xxx/venv/lib/python2.7/site-packages/GPlayCli-0.2.8.post1-py2.7.egg/EGG-INFO/scripts/gplaycli", line 505, in main
  File "/home/xxx/venv/lib/python2.7/site-packages/GPlayCli-0.2.8.post1-py2.7.egg/EGG-INFO/scripts/gplaycli", line 181, in connect_to_googleplay_api
  File "/home/xxx/venv/lib/python2.7/site-packages/GPlayCli-0.2.8.post1-py2.7.egg/EGG-INFO/scripts/gplaycli", line 364, in raw_search
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 200, in search
**IndexError: list index out of range**

I also tried gplaycli-0.2.8 instead of 0.2.8.post1. And also 0.2.7 which also has same problem.
I use the default token-dispenser server, and changed androidId(any help?), still I can't download any app.
BTW. I use proxychains as a proxy.
Hope some advice can help, thank you!

**Comment by Elasti-Shabbir** [comment]
same error here.

**Comment by matlink** [comment]
Sounds like your token is expired. Try to remove ~/.cache/gplaycli/token

**Comment by xhzhang** [comment]
it works! Thanks a lot!
